name: "✨ Feature Request"
description: Propose a new capability or enhancement
title: "[Feature] <short description>"
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Need something that TaintGovernor doesn’t do yet?  
        Tell us why it matters.
  - type: textarea
    id: problem
    attributes:
      label: What problem will this solve?
      render: markdown
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Describe the solution you’d like
      render: markdown
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you’ve considered
      render: markdown
  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - P0 – Blocker
        - P1 – Important
        - P2 – Nice to have
